apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "argo-istio.fullname" . }}-virtualservice
  namespace: argocd
spec:
  hosts:
  - "{{ .Values.service.dns }}"
  gateways:
  - http-gateway-argocd
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: argocd-server